### ISSUE TITLE
Failed to read uuid:seqno and wsrep_gtid_domain_id from joiner script

### ISSUE THREAD

**Issue by yogiGueta** [gregnuj/docker-mariadb-galera-swarm#1]
Hi,
I am using  your image and i am facing a little problem:
When i'm deploying my cluster for the first time everything is ok, but if i do "docker stack rm my-cluster-name..." and then "docker deploy --compose-file my-cluster-compose.yaml..." (deploy it again without deleting the volume "data-dev") i am getting:
 [ERROR] WSREP: Process completed with error: wsrep_sst_xtrabackup-v2 --role 'joiner' --address '10.0.0.3' --data-dev '/var/lib/mysql/'   --parent '1'  '' : 2 (No such file or directory)
2017-05-08 12:42:09 140713715037952 [ERROR] WSREP: Failed to read uuid:seqno and wsrep_gtid_domain_id from joiner script.
2017-05-08 12:42:09 140714095916992 [ERROR] WSREP: SST failed: 2 (No such file or directory)
and after that the cluster is down....
How can i fix it?
Thanks.

**Comment by gregnuj** [comment]
Sorry I have not kept up with this, this project is deprecated at this point, but I can say it is likely better to just spin up mariadb containers and then configure galera manually.
