### ISSUE TITLE
cluster recovery after

### ISSUE THREAD

**Issue by pavimus** [gregnuj/docker-mariadb-galera-swarm#2]
First of all, i want to say thanks to all developers of this container. You doing most userfriendly and great galera container available!

Did someone tested cluster recovering after failures? May be i'm doing something wrong, but after test i am very afraid to use galera cluster inside docker. Before each test i have cluster from 3 nodes, each on different virtual server.

scenario 1:
1) immediate poweroff of VM1, and poweron it again. Result: all is ok, cluster synced.
2) immediate poweroff of VM2, and poweron it again. Result: all is ok, cluster synced.
3) immediate poweroff of VM3, and poweron it again. Result: according to wresp status i got 2 clusters, one has 2 nodes, other - one node on VM3

scenario 2:
1) immediate poweroff of VM1 and VM2, and poweron them again. After that i got cluster from 1 and can't figure how to help join other nodes to it. Tried to execute 'SET GLOBAL wsrep_provider_options='pc.bootstrap=true';' without success

scenario 3:
1) correct poweroff all VMS, and powerup them again. After that cluster was completely broken.

**Comment by gregnuj** [comment]
Sorry I have not kept up with this, this project is deprecated at this point, but I can say it is likely better to just spin up mariadb containers and then configure galera manually.
